### ISSUE TITLE
Suggestion: Add Windows Edition to the OS-Line and Build number

### ISSUE THREAD

**Issue by BoxedLight** [nepnep39/neofetch-win#10]
It would be cool if instead of "OS: Windows 10" or "OS: Windows 11" there would be also the Edition like "OS: Windows 10 Pro" or "OS: Windows 11 Enterprise" so that the edition would be also displayed.

Also, I kinda also want the Build number also shown just like the Linux pendant where you could see which kernel version you are on. Something like

```
OS: Windows 10 Home
Build: 21H2 (XXXXX.XXXX)
```

This is just a suggestion that in my opinion would make neofetch better. Nothing that has to be done. Just a nice little gimmick.

**Comment by nepnep39** [comment]
will do this in the next release

**Comment by nepnep39** [comment]
![image](https://github.com/nepnep39/neofetch-win/assets/119973523/376e9de8-7332-49d2-8178-055cab432850)
