### ISSUE TITLE
GPU says Unknown even after running WinSAT

### ISSUE THREAD

**Issue by matte22ladde** [nepnep39/neofetch-win#11]
The "winsat" command is not missing. This command "wmic path win32_VideoController get name" produces an actual results if that helps.

**Comment by nepnep39** [comment]
does your Windows registry have a key at "SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\WinSAT" ?

**Comment by matte22ladde** [comment]
There's "WindowsExperienceIndexOemInfo" but it's empty.

**Comment by nepnep39** [comment]
![image](https://github.com/nepnep39/neofetch-win/assets/119973523/366b4ec6-4e66-4f47-b6a6-e21a3cbecffa)
is the key above it empty?

**Comment by matte22ladde** [comment]
No, the key above, which was supposed to be "WindowsExperienceIndexOemInfo," which no longer exists after I reinstalled Windows 10, is not empty. There are four DWORD values. They are "CKCLStart", "WsSwapInterference", "WsSwapResult", and "WsSwapThroughput" whose data are "0", "2686992", "452608", and "452608," respectively.

**Comment by nepnep39** [comment]
there should be many more DWORDS, as well as three strings
![image](https://github.com/nepnep39/neofetch-win/assets/119973523/e0eb1218-a642-4243-81b6-2b43522f621d)
it looks like it might be an issue with your windows install and/or the registry itself, which in that case is an issue i cannot fix

**Comment by matte22ladde** [comment]
Running "winsat formal" now fixes the issue. Maybe it has something to do with the previous state before reinstalling Windows. Just write this off as an user error. Keep up the good work.

**Comment by nepnep39** [comment]
thank you, glad things worked out
