### ISSUE TITLE
it would be great to add more parameters and custom features to it

### ISSUE THREAD

**Issue by PicturePig** [nepnep39/neofetch-win#13]
it would be great to add more parameters and custom features to it

like adding support for arguments like --help or /? or help cmd or even a --version 

or adding custom ASCII Arts...
       
                               Thanks for reading

**Comment by nepnep39** [comment]
it supports custom ASCII art, just needs to be recompiled
I purposefully didn't add any arguments to make it as simple as possible

**Comment by PicturePig** [comment]
that is what i am talking about, it would be great if we add custom ascii files
else it similar to the thing 
```
everything is open source if you can read assembly
```
though neofetch-win is FOSS and great but if we could add ascii art in another file that would be better...
or having at least different headers for arts when recompiling :)

still it is amazing, thanks for reading

**Comment by nepnep39** [comment]
take a look at art.h, I wrote it in a way so that you can easily customize it

**Comment by PicturePig** [comment]
oh ok, but can you still add that parameter feature? if it still counts as a low weight neofetch alternative for windows?

btw you can use "type" command in windows to display content of a file in console like "cat" in bash

**Comment by nepnep39** [comment]
im not going to implement that because it goes against my vision for it being as simple as possible but you can fork it and give it a go
