### ISSUE TITLE
color palette overflow

### ISSUE THREAD

**Issue by XIYO** [nepnep39/neofetch-win#15]
![image](https://github.com/nepnep39/neofetch-win/assets/27078637/f434b17d-7a45-4ea2-82d4-0e4fc974f5d4)

Hello,
I've used a translator, so please understand if the tone comes across as impolite.

I use the terminal at a quarter of its original size. The color palette looks weird if it goes beyond its designated area.

Is there a way to display the output in two lines, similar to how neofetch does it?

**Comment by nepnep39** [comment]
there is no way to display the colour in two lines right now but i could possibly implement it, let me see what i can do

**Comment by nepnep39** [comment]
![image](https://github.com/nepnep39/neofetch-win/assets/119973523/655f0c70-68a7-4c7a-8248-80ee7ea8ed19)
working on something

**Comment by XIYO** [comment]
my environment- windows terminal- powershell 7.3.8Sent from my iPhoneOn Oct 25, 2023, at 1:56 AM, nepnep ***@***.***> wrote:﻿

working on something

**Comment by nepnep39** [comment]
fixed in v1.2.1 (might take a day or two for Microsoft to approve though)
