### ISSUE TITLE
Whore

### ISSUE THREAD

**Issue by Catalyzzt** [nepnep39/neofetch-win#17]
Whore

_Originally posted by @nepnep39 in https://github.com/nepnep39/neofetch-win/issues/16#issuecomment-1778285406_
issue unresolved
![speaking-head](https://user-images.githubusercontent.com/78272915/277839973-7ad636fe-3ff2-4a82-897e-e00dcaddbb9f.png)

**Comment by nepnep39** [comment]
you're a funny guy
