### ISSUE TITLE
OS type lacks a space in the naming.

### ISSUE THREAD

**Issue by WhereIsF1** [nepnep39/neofetch-win#2]
**Bug Description:**
When running neofetch.exe via cmd, the OS type lacks a space in the naming.

**General Information:**
> _Neofetch Version:_
[neofetch-win version v1.0.3](https://github.com/nepnep39/neofetch-win/releases/tag/v1.0.3) 

> _OS (Version):_
Windows 11 Pro for Workstations [64-Bit]
Version 22H2 (Build 22621.1265)

**Screenshot**
![image](https://user-images.githubusercontent.com/99078094/224493169-5a51449c-6f6f-4c45-beee-e63772fc6f8b.png)

**Comment by nepnep39** [comment]
fixed in v1.1.0
