### ISSUE TITLE
Suggestion: allow terminal color change after run

### ISSUE THREAD

**Issue by DanHolli** [nepnep39/neofetch-win#22]
I like color 0a (hacker vision 😜) but if I run color 0a after it makes the entire thing green and will change it to white after running

having an argument for changing the color after would be nice

**Comment by nepnep39** [comment]
if you'd like you can change line 13 to this
`#define setdflt SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), 2)`
looks like this
![image](https://github.com/nepnep39/neofetch-win/assets/119973523/d9f551fb-e3ee-41c9-b787-2f4632566e56)

**Comment by nepnep39** [comment]
closing this since its been a bit but feel free to reopen
