### ISSUE TITLE
GPU is unknown

### ISSUE THREAD

**Issue by dipanjan1992** [nepnep39/neofetch-win#23]
![image](https://github.com/nepnep39/neofetch-win/assets/107064001/73502860-0db6-43d0-beb5-b4ecfbec2c84)

Error Message:
GPU: Unknown (try running WinSAT to fix this)

My GPU is AMD RX 7600

**Comment by nepnep39** [comment]
did you try running WinSAT

**Comment by 4lkanoid** [comment]
He clearly didn't

**Comment by nepnep39** [comment]
> He clearly didn't

lol

**Comment by dipanjan1992** [comment]
Yes I tried running winsat and it's still showing as unknown

**Comment by dipanjan1992** [comment]
> He clearly didn't

How can you tell?

**Comment by nepnep39** [comment]
> Yes I tried running winsat and it's still showing as unknown

do you have a registry key at "SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinSAT" ?

**Comment by dipanjan1992** [comment]
> > Yes I tried running winsat and it's still showing as unknown
> 
> do you have a registry key at "SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinSAT" ?

Yes I have

**Comment by nepnep39** [comment]
nice, glad its working
