### ISSUE TITLE
how to change which gpu to show

### ISSUE THREAD

**Issue by 4lkanoid** [nepnep39/neofetch-win#26]
![image](https://github.com/nepnep39/neofetch-win/assets/113324276/2ab03756-8f66-4341-bb26-be46b47c5fe1)
its showing the igpu instead of the dedicated gpu

**Comment by nepnep39** [comment]
are you running both? your BIOS should automatically disable your igpu when you plug in a dedicated one unless you specifically tell it not to

**Comment by 4lkanoid** [comment]
maybe its nvidia optimus? only using the D. gpu when it requires to?

**Comment by nepnep39** [comment]
in Task Manager which GPU is GPU0? and which is GPU1?

https://files.horizon.pics/31e531e1-f215-43e8-ba51-fd287ccef738?a=517&mime1=image&mime2=png

**Comment by ipisano** [comment]
This is a non-issue, just run `WinSAT formal` using the GPU you want to show up in neofetch.
Perhaps it could be specified in the readme?
![ApplicationFrameHost_RYo3L0hoCV](https://github.com/nepnep39/neofetch-win/assets/18221957/cf0c6237-009b-4396-b423-15b828227d79)

**Comment by nepnep39** [comment]
good to know since I haven't tested it much with multiple gpus... will take note of this
I'll close this ticket but if that doesn't help feel free to reopen it
