### ISSUE TITLE
idk what i did wrong but its not workin [WinError 1005]

### ISSUE THREAD

**Issue by EfeDevirgen** [nepnep39/neofetch-win#28]
![image](https://github.com/nepnep39/neofetch-win/assets/136119810/f1c987fa-50ce-4d51-a11e-fbb100bf033a)
[WinError 1005]=The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that the volume is not corrupted

**Comment by EfeDevirgen** [comment]
i installed it with pip first then when it didnt work i tried winget

i do use revisionOS so maybe thats causing the problem?

**Comment by nepnep39** [comment]
this is not the right project, this seems to be a python program.

**Comment by EfeDevirgen** [comment]
ok thx, i deleted that file and it worked
