### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by minding-myown-business** [nepnep39/neofetch-win#30]
[VirusTotal Report](https://www.virustotal.com/gui/file/400bf98794e8b9a6ee7cf473bd943b8d464c07f02377667bb8ef0463fb36a60a?nocache=1)
It seems that lots of antivirus software are identifying this as a trojan.

**Comment by nepnep39** [comment]
Probably has something to do with the fact that its pulling things from registry keys that most programs would have no need to access
Would consider this a false positive, I will look into this if I find the time but I can assure you the program is 100% safe, and if you don't trust it you can take a look at the source yourself. Feel free to reopen this ticket if you have any other questions though

**Comment by nepnep39** [comment]
update: someone who previously ran a triage on it and submitted a negative review reran it and found that the program making registry activity was actually another process. some vendors still flag it as malicious, that has not changed, but at least this human reviewer can verify that it is safe: https://tria.ge/240603-mxp1gadb99

**Comment by namazso** [comment]
> Probably has something to do with the fact that its pulling things from registry keys that most programs would have no need to access

What your app actually does barely changes the detection counts. The only real solutions are either individually mailing each AV vendor every single release, or just giving up and buying a code signing certificate.

**Comment by nepnep39** [comment]
> > Probably has something to do with the fact that its pulling things from registry keys that most programs would have no need to access
> 
> What your app actually does barely changes the detection counts. The only real solutions are either individually mailing each AV vendor every single release, or just giving up and buying a code signing certificate.

I have looked into a certificate, can't promise anything but its a possibility
