### ISSUE TITLE
Was able to install it , but it does not pull anything... 

### ISSUE THREAD

**Issue by Wizard-Mage** [nepnep39/neofetch-win#34]
![no_fetch](https://github.com/user-attachments/assets/343e8b34-086d-4c0b-bd13-cb1b26bf1fbc)
Did the scoop and git installs , no output 

![scoop](https://github.com/user-attachments/assets/1beceb23-8711-4262-9759-dc751763d444)

**Comment by nepnep39** [comment]
My program isn't on scoop, it's on winget, maybe you have the wrong repo

**Comment by Wizard-Mage** [comment]
> My program isn't on scoop, it's on winget, maybe you have the wrong repo

Ok I see what happened , You are right , I tried this on a diffrent machine and it does work.
