### ISSUE TITLE
Flagged as PUP

### ISSUE THREAD

**Issue by kim-fg** [nepnep39/neofetch-win#35]
I'm running neofetch installed via scoop on Windows 23H2 (22631).
Windows defender flagged the app as "Potentially Unwanted Program".
This is a bad look and did make me think twice. 
I don't know how this could be solved, but I think its important to look into it.
![image](https://github.com/user-attachments/assets/7aa44ce8-a15d-4266-9ab5-a8a8d1074a14)

**Comment by nepnep39** [comment]
most likely can't be solved unless I pay to have the exe signed, I have looked into this extensively and theres not much I can do other than that

**Comment by kim-fg** [comment]
fair enough, i had a small hunch it could be signing related.
and yes, my bad, i did install it through winget.
thanks for looking into it at least.

**Comment by GEOEGII555** [comment]
> most likely can't be solved unless I pay to have the exe signed, I have looked into this extensively and theres not much I can do other than that. also, did you mean winget? my package isn't on scoop but you seem to have the right one in the screenshot

You can submit the file in Windows defender as a false positive so Microsoft removes the detection.
