### ISSUE TITLE
neofetch shows old gpu

### ISSUE THREAD

**Issue by abodxio** [nepnep39/neofetch-win#7]
I had an RTX 2060 before and I replaced it with another gpu but neofetch shows the old one even though I installed the program after replacing the gpu, 
![Screenshot 2023](https://github.com/nepnep39/neofetch-win/assets/71660297/66641e33-e17f-41bd-a0b1-841d364ff2e9)

**Comment by nepnep39** [comment]
run WinSAT and it should update

**Comment by abodxio** [comment]
that worked! thank you (:
